name: Deploy to App Engine

on:
  push:
    branches: [main] # Deploy on pushes to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    # Authenticate using service account
    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with: 
        service_account: 'acne-scan-app-engine-service-a@acnescan-final.iam.gserviceaccount.com'
        credentials_json: '${{ secrets.GOOGLE_CLOUD_KEY }}'

    - name: Inject secrets into app.yaml
      run: |
        echo "env_variables:" >> app.yaml
        echo "  DB_USERNAME: '${{ secrets.DB_USERNAME }}'" >> app.yaml
        echo "  DB_HOST: '${{ secrets.DB_HOST }}'" >> app.yaml
        echo "  DB_PORT: '${{ secrets.DB_PORT }}'" >> app.yaml
        echo "  DB_NAME: '${{ secrets.DB_NAME }}'" >> app.yaml
        echo "  DB_PASSWORD: '${{ secrets.DB_PASSWORD }}'" >> app.yaml
        echo "  JWT_SECRET: '${{ secrets.JWT_SECRET }}'" >> app.yaml
        echo "  BUCKET_NAME: '${{ secrets.BUCKET_NAME }}'" >> app.yaml
        echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" | sed 's/^/    /' >> app.yaml 

    - name: Deploy to App Engine
      run: gcloud app deploy app.yaml --quiet




    # # Set up Google Cloud SDK
    # - name: Setup Google Cloud SDK
    #   uses: google-github-actions/setup-gcloud@v2

    # # Deploy to Google App Engine
    # - name: Deploy to App Engine
    #   run: |
    #     gcloud app deploy app.yaml --quiet
